### ISSUE TITLE
_objects will retain the delegates

### ISSUE THREAD

**Issue by mattjgalloway** [fphilipe/PHFDelegateChain#1]
I think there is a major flaw with this approach in that the array of delegates will strongly hold onto the delegates. Or have I missed something?

**Comment by fphilipe** [comment]
Yeah, you're totally right about this. I looked into possible workarounds and found [this category](http://ofcodeandmen.poltras.com/2009/08/26/nsmutablearray-with-weak-references/) that hooks into CF to create an array while specifying the retain and release callbacks.

Any thoughts about it?

**Comment by mattjgalloway** [comment]
Absolutely. Just get a CFMutableArrayRef and supply a callback for retain which doesn't actually retain (take that category as an example) and then you can use toll-free bridging from then on to use it as an NSMutableArray.
