### ISSUE TITLE
Crash in methodSignatureForSelector when device has VoiceOver Enabled

### ISSUE THREAD

**Issue by jlindenbaum** [fphilipe/PHFDelegateChain#3]
http://crashes.to/s/1e60c24e944

Possibly related to fphilipe/PHFComposeBarView#41

**Comment by zsk425** [comment]
@jlindenbaum 
I encountered the same problem.But it not happened in methodSignatureForSelector:,the following is my stack info:

![Code](http://7u2iw4.com1.z0.glb.clouddn.com/imagesPHF2.png)

![stack](http://7u2iw4.com1.z0.glb.clouddn.com/imagesPHFCrash.png)
